/* ==========================================
 * Code generated by: Claude AI
 * Modified by: Me (see inline comments)
 * ========================================== */
// [Modified by Me]: Configured API_URL to match local Flask server port
const API_URL = "http://136.66.121.44:5000/api";

let editId = "";

let currentMembers = [];

window.onload = function () {
  loadMembers();
  loadSummary();
  loadExpiringSoon();
};

function isValidEmail(email) {
  const pattern = /^[^@\s]+@[^@\s]+\.[^@\s]+$/;
  return pattern.test(email);
}

function isValidPhone(phone) {
  const pattern = /^[0-9]{7,15}$/;
  return pattern.test(phone);
}

function validateForm(name, email, phone, joinDate, expiryDate) {
  if (name.trim() === "") {
    return "Name is required.";
  }
  if (!isValidEmail(email)) {
    return "Please enter a valid email address.";
  }
  if (!isValidPhone(phone)) {
    return "Phone number must be digits only (7-15 numbers).";
  }
  if (joinDate === "") {
    return "Please choose a join date.";
  }
  if (expiryDate === "") {
    return "Please choose an expiry date.";
  }
  if (expiryDate < joinDate) {
    return "Expiry date cannot be before the join date.";
  }
  return ""; // no errors
}

function loadSummary() {
  fetch(API_URL + "/summary")
    .then(response => response.json())
    .then(data => {
      document.getElementById("totalCount").innerText = data.total;
      document.getElementById("activeCount").innerText = data.active;
      document.getElementById("inactiveCount").innerText = data.inactive;
      document.getElementById("expiringCount").innerText = data.expiring_soon;
    });
}

function loadExpiringSoon() {
  fetch(API_URL + "/members/expiring")
    .then(response => response.json())
    .then(data => showExpiringSoon(data));
}

function showExpiringSoon(members) {
  const table = document.getElementById("expiringTable");

  table.innerHTML = `
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Expiry Date</th>
    </tr>
  `;

  if (members.length === 0) {
    const row = document.createElement("tr");
    row.innerHTML = `<td colspan="3">No memberships expiring in the next 14 days.</td>`;
    table.appendChild(row);
    return;
  }

  for (let i = 0; i < members.length; i++) {
    const m = members[i];
    const row = document.createElement("tr");
    row.innerHTML = `
      <td>${m.name}</td>
      <td>${m.email}</td>
      <td>${m.expiry_date}</td>
    `;
    table.appendChild(row);
  }
}

function loadMembers() {
  fetch(API_URL + "/members")
    .then(response => response.json())
    .then(data => {
      currentMembers = data;
      showMembers(data);
    });
}

function searchMembers() {
  const text = document.getElementById("searchInput").value;
  fetch(API_URL + "/members/search?q=" + text)
    .then(response => response.json())
    .then(data => {
      currentMembers = data;
      showMembers(data);
    });
}

// [Modified by Me]: I wrote the core DOM manipulation logic here.
// It loops through the JSON data from the API and dynamically builds
// the HTML table rows. It also adds a special CSS class for members expiring soon.
function showMembers(members) {
  const table = document.getElementById("memberTable");

  table.innerHTML = `
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Membership</th>
      <th>Join Date</th>
      <th>Expiry Date</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>
  `;

  const today = new Date();
  const in14Days = new Date();
  in14Days.setDate(today.getDate() + 14);
  const todayText = today.toISOString().split("T")[0];
  const in14DaysText = in14Days.toISOString().split("T")[0];

  for (let i = 0; i < members.length; i++) {
    const m = members[i];
    const row = document.createElement("tr");

    const isExpiringSoon = m.expiry_date >= todayText && m.expiry_date <= in14DaysText;
    if (isExpiringSoon) {
      row.classList.add("expiringRow");
    }

    row.innerHTML = `
      <td>${m.name}</td>
      <td>${m.email}</td>
      <td>${m.phone}</td>
      <td>${m.membership_type}</td>
      <td>${m.join_date}</td>
      <td>${m.expiry_date}</td>
      <td>${m.status}</td>
      <td>
        <button onclick="editMember('${m._id}', '${m.name}', '${m.email}', '${m.phone}', '${m.membership_type}', '${m.join_date}', '${m.expiry_date}', '${m.status}')">Edit</button>
        <button onclick="deleteMember('${m._id}')">Delete</button>
        <button onclick="renewMember('${m._id}')">Renew</button>
      </td>
    `;

    table.appendChild(row);
  }
}

// [Modified by Me]: I added these sorting functions so the user
// can sort the list in the browser without having to make extra calls
// to the API, making the app feel much faster.
function sortByName() {
  const sorted = currentMembers.slice(); // copy the list
  sorted.sort(function (a, b) {
    return a.name.localeCompare(b.name);
  });
  showMembers(sorted);
}

function sortByExpiry() {
  const sorted = currentMembers.slice(); // copy the list
  sorted.sort(function (a, b) {
    return a.expiry_date.localeCompare(b.expiry_date);
  });
  showMembers(sorted);
}

function addMember() {
  const name = document.getElementById("nameInput").value;
  const email = document.getElementById("emailInput").value;
  const phone = document.getElementById("phoneInput").value;
  const membership_type = document.getElementById("membershipInput").value;
  const join_date = document.getElementById("joinDateInput").value;
  const expiry_date = document.getElementById("expiryDateInput").value;
  const status = document.getElementById("statusInput").value;

  const errorMessage = validateForm(name, email, phone, join_date, expiry_date);
  if (errorMessage !== "") {
    document.getElementById("formMessage").innerText = errorMessage;
    return;
  }

  fetch(API_URL + "/members", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ name, email, phone, membership_type, join_date, expiry_date, status })
  })
    .then(response => response.json())
    .then(data => {
      document.getElementById("formMessage").innerText = data.message || data.error;
      clearForm();
      loadMembers();
      loadSummary();
      loadExpiringSoon();
    });
}

function editMember(id, name, email, phone, membership_type, join_date, expiry_date, status) {
  editId = id;

  document.getElementById("nameInput").value = name;
  document.getElementById("emailInput").value = email;
  document.getElementById("phoneInput").value = phone;
  document.getElementById("membershipInput").value = membership_type;
  document.getElementById("joinDateInput").value = join_date;
  document.getElementById("expiryDateInput").value = expiry_date;
  document.getElementById("statusInput").value = status;

  document.getElementById("updateBtn").style.display = "inline";
  document.getElementById("cancelBtn").style.display = "inline";
}

function updateMember() {
  const name = document.getElementById("nameInput").value;
  const email = document.getElementById("emailInput").value;
  const phone = document.getElementById("phoneInput").value;
  const membership_type = document.getElementById("membershipInput").value;
  const join_date = document.getElementById("joinDateInput").value;
  const expiry_date = document.getElementById("expiryDateInput").value;
  const status = document.getElementById("statusInput").value;

  const errorMessage = validateForm(name, email, phone, join_date, expiry_date);
  if (errorMessage !== "") {
    document.getElementById("formMessage").innerText = errorMessage;
    return;
  }

  fetch(API_URL + "/members/" + editId, {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ name, email, phone, membership_type, join_date, expiry_date, status })
  })
    .then(response => response.json())
    .then(data => {
      document.getElementById("formMessage").innerText = data.message || data.error;
      cancelEdit();
      loadMembers();
      loadSummary();
      loadExpiringSoon();
    });
}

function cancelEdit() {
  editId = "";
  clearForm();
  document.getElementById("updateBtn").style.display = "none";
  document.getElementById("cancelBtn").style.display = "none";
}

function deleteMember(id) {
  fetch(API_URL + "/members/" + id, { method: "DELETE" })
    .then(response => response.json())
    .then(data => {
      document.getElementById("formMessage").innerText = data.message;
      loadMembers();
      loadSummary();
      loadExpiringSoon();
    });
}

function exportMembers() {
  window.open(API_URL + "/members/export");
}

function renewMember(id) {
  const daysText = prompt("Renew membership for how many days?", "30");

  if (daysText === null) {
    return; // staff clicked Cancel
  }

  const days = parseInt(daysText);

  if (isNaN(days) || days <= 0) {
    document.getElementById("formMessage").innerText = "Please enter a valid number of days.";
    return;
  }

  fetch(API_URL + "/members/" + id + "/renew", {
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ days: days })
  })
    .then(response => response.json())
    .then(data => {
      document.getElementById("formMessage").innerText = data.message + " New expiry: " + data.new_expiry_date;
      loadMembers();
      loadSummary();
      loadExpiringSoon();
    });
}

function clearForm() {
  document.getElementById("nameInput").value = "";
  document.getElementById("emailInput").value = "";
  document.getElementById("phoneInput").value = "";
  document.getElementById("membershipInput").value = "Basic";
  document.getElementById("joinDateInput").value = "";
  document.getElementById("expiryDateInput").value = "";
  document.getElementById("statusInput").value = "Active";
}
