# ==========================================
# Code generated by: Claude AI
# Modified by Me: (see inline comments)
# ==========================================
import re
import csv
import io
from datetime import date, timedelta
from flask import Flask, request, jsonify, Response
from flask_cors import CORS
import database

app = Flask(__name__)
# [Modified by Me]: Added CORS support to allow frontend connection
CORS(app)  # allows our frontend html page to call this API

def is_valid_email(email):
    pattern = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"
    return re.match(pattern, email) is not None

def is_valid_phone(phone):
    return phone.isdigit() and 7 <= len(phone) <= 15

def is_valid_date(text):
    pattern = r"^\d{4}-\d{2}-\d{2}$"
    return re.match(pattern, text) is not None

# [Modified by Me]: I wrote this one validation logic from chatgpt and then others are written by me to ensure
# all data coming from the frontend is clean and meets gym policies
# before saving to the database.
def check_member_data(data):
    if not data.get("name") or len(data.get("name").strip()) == 0:
        return "Name is required."

    if not data.get("email") or not is_valid_email(data.get("email")):
        return "Please enter a valid email address."

    if not data.get("phone") or not is_valid_phone(data.get("phone")):
        return "Phone number must contain only digits (7-15 numbers)."

    if data.get("status") not in ["Active", "Inactive"]:
        return "Status must be Active or Inactive."

    if not data.get("join_date") or not is_valid_date(data.get("join_date")):
        return "Please choose a valid joining date."

    if not data.get("expiry_date") or not is_valid_date(data.get("expiry_date")):
        return "Please choose a valid expiry date."

    if data.get("expiry_date") < data.get("join_date"):
        return "Expiry date cannot be before the joining date."

    return None

@app.route("/api/members", methods=["GET"])
def view_members():
    today_text = date.today().strftime("%Y-%m-%d")
    database.auto_update_expired_members(today_text)

    all_members = database.get_all_members()
    return jsonify(all_members)

@app.route("/api/members/export", methods=["GET"])
# [Modified by Me]: Implemented the CSV export logic below.
# I researched how to use Python's io and csv modules to dynamically 
# generate a CSV file in memory and send it as a downloadable response.
# And i got help from one youtube video also to understand the logic 
def export_members():
    all_members = database.get_all_members()

    output = io.StringIO()
    writer = csv.writer(output)

    writer.writerow(["Name", "Email", "Phone", "Membership Type", "Join Date", "Expiry Date", "Status"])

    for m in all_members:
        writer.writerow([
            m["name"], m["email"], m["phone"], m["membership_type"],
            m["join_date"], m["expiry_date"], m["status"]
        ])

    csv_text = output.getvalue()

    return Response(
        csv_text,
        mimetype="text/csv",
        headers={"Content-Disposition": "attachment; filename=flexfit_members.csv"}
    )

@app.route("/api/members", methods=["POST"])
def add_member():
    data = request.get_json()

    error = check_member_data(data)
    if error:
        return jsonify({"error": error}), 400

    existing_member = database.find_member_by_email(data["email"].strip())
    if existing_member:
        return jsonify({"error": "A member with this email already exists."}), 400

    new_member = {
        "name": data["name"].strip(),
        "email": data["email"].strip(),
        "phone": data["phone"].strip(),
        "membership_type": data.get("membership_type", "Basic"),
        "join_date": data["join_date"].strip(),
        "expiry_date": data["expiry_date"].strip(),
        "status": data["status"]
    }

    new_id = database.add_member(new_member)
    return jsonify({"message": "Member added!", "id": new_id}), 201

@app.route("/api/members/search", methods=["GET"])
def search_member():
    text = request.args.get("q", "")
    results = database.search_members(text)
    return jsonify(results)
    
# Modified code get help from GPT and use boiler code
@app.route("/api/members/<member_id>", methods=["PUT"])
def update_member(member_id):
    data = request.get_json()

    error = check_member_data(data)
    if error:
        return jsonify({"error": error}), 400

    existing_member = database.find_member_by_email(data["email"].strip())
    if existing_member and str(existing_member["_id"]) != member_id:
        return jsonify({"error": "A member with this email already exists."}), 400

    updated_data = {
        "name": data["name"].strip(),
        "email": data["email"].strip(),
        "phone": data["phone"].strip(),
        "membership_type": data.get("membership_type", "Basic"),
        "join_date": data["join_date"].strip(),
        "expiry_date": data["expiry_date"].strip(),
        "status": data["status"]
    }

    database.update_member(member_id, updated_data)
    return jsonify({"message": "Member updated!"})

@app.route("/api/members/<member_id>", methods=["DELETE"])
def delete_member(member_id):
    database.delete_member(member_id)
    return jsonify({"message": "Member deleted!"})

@app.route("/api/members/expiring", methods=["GET"])
def expiring_members():
    today = date.today()
    in_14_days = today + timedelta(days=14)
    today_text = today.strftime("%Y-%m-%d")
    in_14_days_text = in_14_days.strftime("%Y-%m-%d")

    results = database.get_expiring_members(today_text, in_14_days_text)
    return jsonify(results)

@app.route("/api/members/<member_id>/renew", methods=["PUT"])
def renew_member(member_id):
    data = request.get_json()
    days = data.get("days", 30)  # how many days to extend membership by

    new_expiry = date.today() + timedelta(days=days)
    new_expiry_text = new_expiry.strftime("%Y-%m-%d")

    database.renew_member(member_id, new_expiry_text)
    return jsonify({"message": "Membership renewed!", "new_expiry_date": new_expiry_text})

@app.route("/api/summary", methods=["GET"])
def summary():
    today = date.today()
    in_14_days = today + timedelta(days=14)
    today_text = today.strftime("%Y-%m-%d")
    in_14_days_text = in_14_days.strftime("%Y-%m-%d")

    database.auto_update_expired_members(today_text)

    counts = database.count_members(today_text, in_14_days_text)
    return jsonify(counts)

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=5000)
