# ==========================================
# Code generated by: Claude AI
# Modified by: Me (see inline comments)
# ==========================================
from pymongo import MongoClient

# [Modified by Me]: Updated MongoDB connection string for my own cluster
client = MongoClient("mongodb+srv://usman014689:usman014689@cluster0.dtdmhjm.mongodb.net/?appName=Cluster0")

db = client["flexfit_db"]

members = db["members"]

def add_member(member):
    result = members.insert_one(member)
    return str(result.inserted_id)

def find_member_by_email(email):
    return members.find_one({"email": email})

def get_all_members():
    all_members = []
    for member in members.find():
        member["_id"] = str(member["_id"])  # convert id to text so it can be sent as JSON
        all_members.append(member)
    return all_members

# [Modified by Me]: I wrote the advanced regex search query here. 
# It uses MongoDB's $or and $regex operators to let users search 
# by either name or email, completely case-insensitive.
def search_members(text):
    query = {
        "$or": [
            {"name": {"$regex": text, "$options": "i"}},
            {"email": {"$regex": text, "$options": "i"}}
        ]
    }
    results = []
    for member in members.find(query):
        member["_id"] = str(member["_id"])
        results.append(member)
    return results

def update_member(member_id, new_data):
    from bson.objectid import ObjectId
    members.update_one({"_id": ObjectId(member_id)}, {"$set": new_data})

def delete_member(member_id):
    from bson.objectid import ObjectId
    members.delete_one({"_id": ObjectId(member_id)})

def get_expiring_members(today_text, in_14_days_text):
    query = {
        "expiry_date": {"$gte": today_text, "$lte": in_14_days_text}
    }
    results = []
    for member in members.find(query):
        member["_id"] = str(member["_id"])
        results.append(member)
    return results

# [Modified by ME]: I implemented the dashboard aggregation logic.
# Instead of doing multiple API calls, I created this single function
# to count total, active, inactive, and soon-to-expire members.
def count_members(today_text, in_14_days_text):
    total = members.count_documents({})
    active = members.count_documents({"status": "Active"})
    inactive = members.count_documents({"status": "Inactive"})
    expiring_soon = members.count_documents({
        "expiry_date": {"$gte": today_text, "$lte": in_14_days_text}
    })
    return {"total": total, "active": active, "inactive": inactive, "expiring_soon": expiring_soon}

def auto_update_expired_members(today_text):
    members.update_many(
        {"expiry_date": {"$lt": today_text}, "status": "Active"},
        {"$set": {"status": "Inactive"}}
    )

def renew_member(member_id, new_expiry_date):
    from bson.objectid import ObjectId
    members.update_one(
        {"_id": ObjectId(member_id)},
        {"$set": {"expiry_date": new_expiry_date, "status": "Active"}}
    )
