# ==========================================
# Code generated by: Claude AI
# Modified by: Me (see inline comments)
# ==========================================
import app

def test_valid_email():
    assert app.is_valid_email("john@example.com") == True

def test_invalid_email():
    assert app.is_valid_email("john@example") == False

def test_valid_phone():
    assert app.is_valid_phone("0871234567") == True

def test_invalid_phone():
    assert app.is_valid_phone("abc123") == False

def test_missing_name_gives_error():
    data = {"name": "", "email": "a@a.com", "phone": "0871234567",
             "join_date": "2026-01-01", "expiry_date": "2026-12-01", "status": "Active"}
    error = app.check_member_data(data)
    assert error == "Name is required."

def test_good_data_has_no_error():
    data = {"name": "John", "email": "john@example.com", "phone": "0871234567",
             "join_date": "2026-01-01", "expiry_date": "2026-12-01", "status": "Active"}
    error = app.check_member_data(data)
    assert error is None

def test_expiry_before_join_gives_error():
    data = {"name": "John", "email": "john@example.com", "phone": "0871234567",
             "join_date": "2026-12-01", "expiry_date": "2026-01-01", "status": "Active"}
    error = app.check_member_data(data)
    assert error == "Expiry date cannot be before the joining date."

def test_add_member_route():
    client = app.app.test_client()

    new_member = {
        "name": "Test User",
        "email": "testuser@example.com",
        "phone": "0851234567",
        "membership_type": "Basic",
        "join_date": "2026-06-01",
        "expiry_date": "2026-07-01",
        "status": "Active"
    }

    response = client.post("/api/members", json=new_member)

    assert response.status_code == 201
    assert "message" in response.get_json()

def test_duplicate_email_is_rejected():
    client = app.app.test_client()

    member = {
        "name": "Duplicate Person",
        "email": "duplicate@example.com",
        "phone": "0851111111",
        "membership_type": "Basic",
        "join_date": "2026-06-01",
        "expiry_date": "2026-07-01",
        "status": "Active"
    }

    first_response = client.post("/api/members", json=member)
    assert first_response.status_code == 201

    second_response = client.post("/api/members", json=member)
    assert second_response.status_code == 400
    assert "already exists" in second_response.get_json()["error"]
